# .circleci/config.yml
version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.18.0

jobs:
  build-and-test:
    executor: node-executor
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm test

  deploy:
    executor: node-executor
    steps:
      - checkout
      - run: echo "Deploy step goes here"

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
