version: 2.1

orbs:
  docker: circleci/docker@2.2.0

executors:
  node-executor:
    docker:
      - image: cimg/node:18.18.0

jobs:
  build-and-test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run linting
          command: npm run lint
      - run:
          name: Run tests
          command: npm test

  build-docker:
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            if [ -z "$DOCKER_LOGIN" ]; then
              echo "DOCKER_LOGIN environment variable is not set"
              exit 1
            fi
            docker build -t $DOCKER_LOGIN/bootcamp-project-2:$CIRCLE_SHA1 .
            docker build -t $DOCKER_LOGIN/bootcamp-project-2:latest .
      - run:
          name: Push to Docker Hub
          command: |
            if [ -z "$DOCKER_LOGIN" ] || [ -z "$DOCKER_PASSWORD" ]; then
              echo "Docker Hub credentials not set"
              exit 1
            fi
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $DOCKER_LOGIN/bootcamp-project-2:$CIRCLE_SHA1
            docker push $DOCKER_LOGIN/bootcamp-project-2:latest

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build-and-test
      - build-docker:
          requires:
            - build-and-test
          filters:
            branches:
              only: main